### PR TITLE
Enhanced and corrected Nextion library version for Arduino/Esp8266/No…

### PR DESCRIPTION
**Pull request by jyberg**
…deMcu, based on original Nextion Arduino library

- Added support for NodeMcu/esp8266, Software serial, Software serial can be used with arduino also
- Added support for global Nextion objects. (Optional page parameter added in the components)
- NexVariable corrected to use int32_t data type
- NextText corrected to return tru/false, and string length is returned in len parameter
- NextText String object support added
- other small bug fixes done
- Added to support global Nextion events like CurrentPageIdCallback,systemStartUpCallback,...
- examples Nextion editor projects corrected

-For some reason I need to remove NexUpload.h & NexUpload.cpp when using the library in PlatformIO
  some platform header files not found spontaneously when building, adding the libray path in platformio.ini did not help.

### CODE REVIEW

**Comment by s-celles** [comment]
It will be great to have this kind of contribution merged upstream!
pinging @itead @shennongmin @zhangabc @hxming123456 @huangxianming

**Comment by s-celles** [comment]
Pinging @ekhiw who can approve a PR
But I'm still wondering who is allowed here to merge such a great PR
That's really problematic.

**Comment by ekhiw** [comment]
@scls19fr you can approve too, I have no right to merge. It seems they no longer support this library.

**Comment by ekhiw** [comment]
pingging @shennongmin who has write access

**Comment by s-celles** [comment]
Sorry @ekhiw but I can't approve only reviewer can.
@shennongmin could you tell us what is locking in merging this PR (and many others)

**Comment by jyberg** [comment]
Hi, this my pull request is outdated, I have done lot of other corrections to my enhanced version over the time. I have also implemented multiple displays support, that is currently under the testing.

**Pull request closed without merging**
